import test from 'node:test';
import assert from 'node:assert/strict';
import { loadConfig } from '../src/config.js';
import { parseInstances, InstanceManager } from '../src/instances.js';
import { PipedClient } from '../src/piped.js';

class Response { constructor(payload, status = 200, text = '') { this.payload = payload; this.status = status; this.ok = status < 400; this.textValue = text; } async json() { return this.payload; } async text() { return this.textValue; } }
function fakeFetch(responses) { const calls = []; const fn = async url => { calls.push(String(url)); const key = String(url).split('?')[0]; const value = responses[key]; if (value instanceof Error) throw value; return value; }; fn.calls = calls; return fn; }
const config = () => ({ ...loadConfig({}), timeoutSeconds: 1 });

test('parses, deduplicates, marks CDN instances, and derives frontends', () => { const result = parseInstances('| API | CDN |\n| https://pipedapi.one | yes |\n| https://pipedapi.one/registered/badge | yes |\n| https://pipedapi.one/ | yes |\n| https://pipedapi.two | no |'); assert.deepEqual(result, [{ url: 'https://pipedapi.one', cdn: true, frontend: 'https://one' }, { url: 'https://pipedapi.two', cdn: false, frontend: 'https://two' }]); });
test('ignores invalid and non-API instances', () => assert.deepEqual(parseInstances('http://api.example\nhttps://piped.video\nnot a URL'), []));
test('health checks and prefers CDN', async () => { const fetcher = fakeFetch({ 'https://pipedapi.one/search': new Response({ items: [] }), 'https://pipedapi.two/search': new Response({ items: [] }) }); const manager = new InstanceManager(config(), fetcher); manager.loadMarkdown('| https://pipedapi.one | no |\n| https://pipedapi.two | CDN |'); assert.equal(await manager.healthCheckAll(), 2); assert.equal(manager.select().url, 'https://pipedapi.two'); });
test('fails over and normalizes search results', async () => { const fetcher = fakeFetch({ 'https://pipedapi.one/search': new Response({ items: [] }), 'https://pipedapi.two/search': new Response({ items: [{ type: 'stream', url: '/watch?v=abc', title: 'A', uploaderName: 'C' }] }) }); const manager = new InstanceManager(config(), fetcher); manager.loadMarkdown('| https://pipedapi.one | CDN |\n| https://pipedapi.two | CDN |'); await manager.healthCheckAll(); const original = fetcher; manager.fetch = async url => { if (String(url).startsWith('https://pipedapi.one/search')) throw new Error('down'); return original(url); }; const result = await new PipedClient(config(), manager).search('runit'); assert.equal(result[0].video_id, 'abc'); });
test('normalizes video streams', async () => { const fetcher = fakeFetch({ 'https://pipedapi.one/search': new Response({ items: [] }), 'https://pipedapi.one/streams/abc': new Response({ videoId: 'abc', title: 'Title', uploader: 'Channel', videoStreams: [{ quality: '720p', url: 'stream' }], audioStreams: [] }) }); const manager = new InstanceManager(config(), fetcher); manager.loadMarkdown('| https://pipedapi.one | CDN |'); await manager.healthCheckAll(); const result = await new PipedClient(config(), manager).video('abc'); assert.equal(result.channel, 'Channel'); assert.equal(result.streams.video[0].quality, '720p'); });
test('encodes playback URL parameters', () => { const manager = new InstanceManager(config(), fakeFetch({})); manager.loadMarkdown('| https://pipedapi.example/path | CDN |'); manager.instances.get('https://pipedapi.example/path').healthy = true; const url = new PipedClient(config(), manager).playbackUrl('abc', { autoplay: true, listen: true, quality: 1080 }); const parsed = new URL(url); assert.equal(parsed.hostname, 'example'); assert.equal(parsed.searchParams.get('instance'), 'https://pipedapi.example/path'); assert.equal(parsed.searchParams.get('playerAutoPlay'), 'true'); });
test('loads configuration from environment', () => { const result = loadConfig({ YOUTUBE_MCP_PORT: '9000', YOUTUBE_MCP_TRANSPORT: 'streamable-http' }); assert.equal(result.port, 9000); assert.equal(result.transport, 'streamable-http'); });
